### ISSUE TITLE
question: Internal service exception

### ISSUE THREAD

**Issue by ashishsakarkar2020** [paypal/PayPal-Android-SDK#188] opened 2015-08-28 12:32 UTC
08-28 17:52:19.352: E/paypal.sdk(23541): request failure with http statusCode:400,exception:org.apache.http.client.HttpResponseException: Bad Request
08-28 17:52:19.353: E/paypal.sdk(23541): request failed with server response:{"name":"VALIDATION_ERROR","details":[{"field":"redirect_urls","issue":"This field required when payment_method is 'paypal'"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR","debug_id":"c06d0b3341353"}
08-28 17:52:19.354: E/PayPalService(23541): VALIDATION_ERROR

The app was working fine till yesterday, however from today i m getting Internal service error. I suspect it is because of the redirect URL settings from the server terminal. So i have set the Return URL to something like this  http://www.xxx.com..... but its still not working

**Comment by jaypatel512** [comment] 2015-09-01 18:01
Closing this issue as it is duplicate of https://github.com/paypal/PayPal-Android-SDK/issues/190

**Closed by jaypatel512** 2015-09-01 18:01 UTC
Labels: question
