### ISSUE TITLE
request failure with http statusCode:422,exception:Unprocessable Entity

### ISSUE THREAD

**Issue by Stefanm89** [paypal/PayPal-Android-SDK#320] opened 2016-08-04 09:14 UTC
Dear all,

I have implemented PayPal Sandbox into my Android application and it worked fine until recently. 

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal Android SDK Version: com.paypal.sdk:paypal-android-sdk:2.14.2
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...): Nexus 5X with Android 6.0
- PayPal-Debug-ID(s) (from any logs):
request failure with http statusCode:422,exception:Unprocessable Entity
request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"e3ca04ed15acc","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
PAYMENT_CREATION_ERROR

I log into my sandbox account and when I try to pay I get the above-mentioned error and a dialog that says Try again.

Regards,
Stefan

**Comment by pp-randy** [comment] 2016-08-04 13:38
Closing as duplicate of https://github.com/paypal/PayPal-Android-SDK/issues/319

**Comment by pp-randy** [comment] 2016-08-04 14:23
@Stefanm89 does your payment work in USD?  Seeing a receiving preference decline but not able to identify an exact cause at this time.

**Comment by Stefanm89** [comment] 2016-08-04 14:34
No, my payment works in ILS. The weird thing, that it used to work before and all of a sudden I get this error.

**Comment by pp-randy** [comment] 2016-08-04 14:45
Will your payments in production be from US based accounts?

**Comment by Stefanm89** [comment] 2016-08-04 14:46
No, they will from Israeli based accounts.

**Comment by pp-randy** [comment] 2016-08-04 14:55
Have you tried using Israel accounts?  If not, you should try to simulate what your production payments would be like.  You can create Israel test accounts them after logging into the Developer site here: https://developer.paypal.com/developer/accounts/create

**Comment by pp-randy** [comment] 2016-08-04 14:56
The error you are receiving is not a helpful error though so I am following up on that as well.

**Comment by Stefanm89** [comment] 2016-08-04 15:01
I've created IL accounts just now, and tried to pay in ILS, but I get the same error. However, if I change it to USD, it works.

**Comment by pp-randy** [comment] 2016-08-04 15:03
With the receiving account also IL?  If so I will try to reproduce as it could be ILS issue in sandbox.

**Comment by pp-randy** [comment] 2016-08-04 15:26
I had success using IL for both the payer and receiver and sending in ILS.

**Comment by pp-randy** [comment] 2016-08-04 15:36
Can you provide the log information for the error when using your IL accounts?

**Comment by Stefanm89** [comment] 2016-08-05 07:26
Yes, this way it works. Thank you for all your effort!

**Closed** 2016-08-05 14:01 UTC
