### ISSUE TITLE
Kotlin crash app when back from PayPalFuturePaymentActivity

### ISSUE THREAD

**Issue by duongnx10m** [paypal/PayPal-Android-SDK#426] opened 2017-08-21 10:51 UTC
### General information

* SDK/Library version: 2.15.3
* Environment: Android SDK
* `PayPal-Debug-ID` values: 
* Android Version and Device: android 6.0

### Issue description
* Open PayPalFuturePaymentActivity
* Then back to the before Activity
* crash happen on onActivityResult(), this bug only happen on kotlin, not happen on java

**Comment by pp-randy** [comment] 2017-08-23 15:56
Is this happening in the sample app?  I am not able to reproduce.

**Comment by jyotisolanki** [comment] 2017-08-30 06:25
Same issue i am getting with Kotlin file. Anyone find solution. and also i have check with Sample app Kotlin. in this also not working getting crash.

**Comment by jyotisolanki** [comment] 2017-08-31 07:51
Hii ,
i have resolved this issue just check data for null condition : @Nullable data: Intent? and It works

override fun onActivityResult(requestCode: Int, resultCode: Int, @Nullable data: Intent?) {
        if (requestCode == REQUEST_CODE_PAYMENT) {
 if(data!=null) {
                try {

            if (resultCode == Activity.RESULT_OK) {
                val confirm = data.getParcelableExtra<PaymentConfirmation>(PaymentActivity.EXTRA_RESULT_CONFIRMATION)
                if (confirm != null) {
                    try {
                        Log.i(TAG, confirm.toJSONObject().toString(4))
                        Log.i(TAG, confirm.payment.toJSONObject().toString(4))
                        /**
                         * TODO: send 'confirm' (and possibly confirm.getPayment() to your server for verification
                         * or consent completion.
                         * See https://developer.paypal.com/webapps/developer/docs/integration/mobile/verify-mobile-payment/
                         * for more details.

                         * For sample mobile backend interactions, see
                         * https://github.com/paypal/rest-api-sdk-python/tree/master/samples/mobile_backend
                         */
                        displayResultText("PaymentConfirmation info received from PayPal")

   } catch (e: JSONException) {
                                println("Exception json" + e.message)
                                Log.e(TAG, "an extremely unlikely failure occurred: ", e)
                            }
                            catch (e: Exception) {
                                println("Exception in" + e.message)
                                Log.e(TAG, "an extremely unlikely failure occurred: ", e)
                            }

                        }
                    } else if (resultCode == Activity.RESULT_CANCELED && data == null) {
                        activity.finish()
                        Toast.makeText(activity, "The user canceled", Toast.LENGTH_LONG).show()
                        Log.i(TAG, "The user canceled.")
                        return
                    } else if (resultCode == PaymentActivity.RESULT_EXTRAS_INVALID && data == null) {
                        activity.finish()
                        Toast.makeText(activity, "The user canceled", Toast.LENGTH_LONG).show()
                        Log.i(
                                TAG,
                                "An invalid Payment or PayPalConfiguration was submitted. Please see the docs.")
                    }

                } catch (e: Exception) {
println("Exception out" + e.message)
                }

            }
        } else if (requestCode == REQUEST_CODE_FUTURE_PAYMENT) {
            if (resultCode == Activity.RESULT_OK) {
                val auth = data.getParcelableExtra<PayPalAuthorization>(PayPalFuturePaymentActivity.EXTRA_RESULT_AUTHORIZATION)
                if (auth != null) {
                    try {
                        Log.i("FuturePaymentExample", auth.toJSONObject().toString(4))

                        val authorization_code = auth.authorizationCode
                        Log.i("FuturePaymentExample", authorization_code)

                        sendAuthorizationToServer(auth)
                        displayResultText("Future Payment code received from PayPal")

                    } catch (e: JSONException) {
                        Log.e("FuturePaymentExample", "an extremely unlikely failure occurred: ", e)
                    }

                }
            } else if (resultCode == Activity.RESULT_CANCELED) {
                Log.i("FuturePaymentExample", "The user canceled.")
            } else if (resultCode == PayPalFuturePaymentActivity.RESULT_EXTRAS_INVALID) {
                Log.i(
                        "FuturePaymentExample",
                        "Probably the attempt to previously start the PayPalService had an invalid PayPalConfiguration. Please see the docs.")
            }
        } else if (requestCode == REQUEST_CODE_PROFILE_SHARING) {
            if (resultCode == Activity.RESULT_OK) {
                val auth = data.getParcelableExtra<PayPalAuthorization>(PayPalProfileSharingActivity.EXTRA_RESULT_AUTHORIZATION)
                if (auth != null) {
                    try {
                        Log.i("ProfileSharingExample", auth.toJSONObject().toString(4))

                        val authorization_code = auth.authorizationCode
                        Log.i("ProfileSharingExample", authorization_code)

                        sendAuthorizationToServer(auth)
                        displayResultText("Profile Sharing code received from PayPal")

                    } catch (e: JSONException) {
                        Log.e("ProfileSharingExample", "an extremely unlikely failure occurred: ", e)
                    }

                }
            } else if (resultCode == Activity.RESULT_CANCELED) {
                Log.i("ProfileSharingExample", "The user canceled.")
            } else if (resultCode == PayPalFuturePaymentActivity.RESULT_EXTRAS_INVALID) {
                Log.i(
                        "ProfileSharingExample",
                        "Probably the attempt to previously start the PayPalService had an invalid PayPalConfiguration. Please see the docs.")
            }
        }
    }

**Comment by xiaoleih41** [comment] 2017-08-31 19:30
Close this issue as it appears to be solved.

**Closed by xiaoleih41** 2017-08-31 19:30 UTC
Labels: question
