### ISSUE TITLE
PAYMENT_CREATION_ERROR [33d54a0ac2b54]

### ISSUE THREAD

**Issue by markserbol** [paypal/PayPal-Android-SDK#315] opened 2016-08-01 09:50 UTC
### Required Information

- Mode (Mock/Sandbox/Live): **Sandbox**
- PayPal Android SDK Version: **2.14.4**
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...): **Nexus 5 with Android 6.0.1**
- PayPal-Debug-ID(s) (from any logs): **33d54a0ac2b54**

### Issue Description
I'm using the SDK together with `PayPal-Cordova-Plugin` for my ionic project and it seems I can't complete the payment on sandbox. It says `There was a problem setting up this payment. Please visit the PayPal website to check your account`.

Here's the log: 
````sh
08-01 17:30:54.586  3639  4400 W paypal.sdk: fg SN:11 PayPal Debug-ID: 33d54a0ac2b54 [sandbox, 2.14.4;release]
08-01 17:30:54.586  3639  4400 E paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
08-01 17:30:54.587  3639  4400 E paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"33d54a0ac2b54","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
08-01 17:30:54.587  3639  4400 E paypal.sdk: 
08-01 17:30:54.590  3639  3639 E paypal.sdk: PAYMENT_CREATION_ERROR
````

Please help me identify the issue. Thanks!

**Comment by jaypatel512** [comment] 2016-08-01 15:33
Hey @markserbol !

Just curious, have you gone through the basic example, to make sure your integration is correct ? https://github.com/paypal/PayPal-Cordova-Plugin#basic-example-of-the-app. 

I will try to reproduce the issue and get back to you.

**Comment by jaypatel512** [comment] 2016-08-01 17:03
Btw, this looks like a duplicate of https://github.com/paypal/PayPal-Cordova-Plugin/issues/194. 
Closing this issue. Please relay conversations to Cordova Plugin Repository.

**Closed by jaypatel512** 2016-08-01 17:03 UTC
Labels: question
