### ISSUE TITLE
Checkout session not created error

### ISSUE THREAD

**Issue by hackerutsav** [paypal/PayPal-Android-SDK#385] opened 2017-02-17 12:52 UTC
- Mode (Live):
- PayPal Android SDK Version: 2.15.3
- Android Version and Device (6.0.1,Motorola G3):
- PayPal-Debug-ID(s) (6fbbf47861810):

### Issue Description
I have integrated Paypal SDK into my android app.While paying,after logging into my paypal account with valid USD(0.6),my transaction cost is (0.1),i keep getting this log: ({"name":"PAYMENT_CREATION_ERROR","debug_id":"6fbbf47861810","message":"checkout-session notcreated","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}). Screenshot-->
![whatsapp image 2017-02-17 at 6 09 53 pm](https://cloud.githubusercontent.com/assets/3045655/23065878/bdda32d8-f53d-11e6-9759-e83d8d453595.jpg)

Please help as our app is stuck due to paypal payments not being integrated.

**Comment by bluk** [comment] 2017-03-06 15:58
@hackerutsav Sorry for the delay in response. Does this error occur on only one device or multiple ones?

If you can, please contact [PayPal Support](https://developer.paypal.com/support/) with more details.

**Comment by pp-randy** [comment] 2017-03-28 15:32
Closing the issue, please let us know if further assistance is needed.

**Closed by pp-randy** 2017-03-28 15:32 UTC

**Comment by tahafarooqui** [comment] 2018-01-16 21:54
Same Here, It is not working

**Comment by xiaoleih41** [comment] 2018-01-17 17:27
This is normally a transaction or account specific issue. Please contact customer service number listed on your account to get the specific reason for the transaction failure.  Lock this thread for further discussion as the issue is normally not a technical issue and the original issue was solved.
