### ISSUE TITLE
How to get paypal email after payment is successful

### ISSUE THREAD

**Issue by meet2011** [paypal/PayPal-Android-SDK#200] opened 2015-09-29 20:12 UTC
I am trying to get paypal email after user has paid through paypal. Because we have to use the paypal email further in our application. 

I checked in OnActivityResult but it doesn't send paypal email but if we use MPL library then it sends paypal email in response.

**Comment by jaypatel512** [comment] 2015-09-29 20:18
Duplicate of https://github.com/paypal/PayPal-Android-SDK/issues/162

**Closed by jaypatel512** 2015-09-29 20:18 UTC
Labels: question
