### ISSUE TITLE
rememberUser(false) is not working

### ISSUE THREAD

**Issue by NadeemClabs** [paypal/PayPal-Android-SDK#265] opened 2016-02-25 13:33 UTC
Hi,

If I pass false in rememberUser(boolean) method, I goy stuck on Checking this device while its work fine if I pass true as param or just remove it.
Please look into it I need urgent help.

**Comment by pp-randy** [comment] 2016-02-25 14:49
Appears duplicate of https://github.com/paypal/PayPal-Android-SDK/issues/264

**Closed by pp-randy** 2016-02-25 14:49 UTC
Labels: duplicate
