### ISSUE TITLE
Paypal Profile Sharing on Fragment

### ISSUE THREAD

**Issue by GeylaniArca** [paypal/PayPal-Android-SDK#376] opened 2016-12-27 15:54 UTC
I can't see permision page after login page. You can check link for details.
http://stackoverflow.com/questions/41347998/paypal-profile-sharing-on-fragment

**Comment by ppmtscory** [comment] 2017-01-06 16:57
Are you able to reproduce this with the sample app from the SDK as everything is working fine for me there?  What scopes are you passing and have you tried the sandbox environment in lieu of `ENVIRONMENT_NO_NETWORK`?  When you get back to the `onActivityResult`, what are the values for `requestCode`, `resultCode`, and `data`?

**Comment by pp-randy** [comment] 2017-03-28 16:56
Closing the issue due to no further response being provided, please let us know if we need to assist further.

**Closed by pp-randy** 2017-03-28 16:56 UTC
Labels: question

**Comment by GeylaniArca** [comment] 2017-03-29 09:46
I'm sorry for late reply. I solved the problem. 
http://stackoverflow.com/a/10564488/3141750

**Comment by pp-randy** [comment] 2017-03-29 15:08
Thank you for following up with the resolution.  We appreciate it, in case others experience similar issues.
