### ISSUE TITLE
Paypal Android SDK Internal Service Error 

### ISSUE THREAD

**Issue by navrajred** [paypal/PayPal-Android-SDK#214] opened 2015-10-27 10:16 UTC
When i am trying to make a payment with Android Paypal SDK i am getting an internal service Error.
```java
thingToBuy = new PayPalPayment(new BigDecimal("10"), "USD",
                        "HeadSet", PayPalPayment.PAYMENT_INTENT_SALE);
                Intent intent = new Intent(PaypalActivity.this,
                        PaymentActivity.class);
                intent.putExtra(PaymentActivity.EXTRA_PAYMENT, thingToBuy);
                startActivityForResult(intent, REQUEST_CODE_PAYMENT);
```
This is how i am calling the request

```
 15:46:07.748 30965-31482/revealio.michelle.com.revealio W/paypal.sdk: X SN:22 PayPal Debug-ID: 1f0f1b1262b6d [sandbox, 2.1.0;release]
10-27 15:46:07.748 30965-31482/revealio.michelle.com.revealio E/paypal.sdk: request failure with http statusCode:500,exception:org.apache.http.client.HttpResponseException: Internal Server Error
10-27 15:46:07.748 30965-31482/revealio.michelle.com.revealio E/paypal.sdk: request failed with server response:{"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"1f0f1b1262b6d"}
10-27 15:46:07.749 30965-30965/revealio.michelle.com.revealio E/PayPalService: INTERNAL_SERVICE_ERROR
```

**Comment by navrajred** [comment] 2015-10-27 10:36
.environment(PayPalConfiguration.ENVIRONMENT_NO_NETWORK)

when this environment is set the Transaction is happening.
However when the line is replaced with this'
PayPalConfiguration.ENVIRONMENT_SANDBOX;

i get a 500 error. is something wrong with Sandbox Environment?

**Comment by jaypatel512** [comment] 2015-10-30 00:17
Just out of curiosity, did you change the ClientId, as shown [here](https://github.com/paypal/PayPal-Android-SDK/blob/master/SampleApp/src/main/java/com/paypal/example/paypalandroidsdkexample/SampleActivity.java#L51) ?

**Comment by jaypatel512** [comment] 2015-10-30 06:01
Duplicate of https://github.com/paypal/PayPal-iOS-SDK/issues/355

**Closed by jaypatel512** 2015-10-30 06:01 UTC
Labels: question
