### ISSUE TITLE
Unable to merge dex (Android Studio 3.0)

### ISSUE THREAD

**Issue by SalvatoreAD** [paypal/PayPal-Android-SDK#448] opened 2017-10-26 09:50 UTC
### General information

* SDK/Library version:  2.15.3 (Android studio 3.0)
* Environment:  Sandbox
* `PayPal-Debug-ID` values: 
* Android Version and Device:  Android 6.0

### Issue description

When i insert this in builg.gradle

`    compile 'com.paypal.sdk:paypal-android-sdk:2.15.3'
`
I have this error

```
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```

**Comment by xiaoleih41** [comment] 2017-10-26 18:04
This SDK has been deprecated. If you have not yet been approved for production environment, please use Braintree Direct in supported countries. In other countries, use Express Checkout and choose the Braintree SDK integration option.

**Comment by jaypatel512** [comment] 2017-10-30 17:39
Hey @SalvatoreAD !

We were not able to replicate this error on Android Studio 3.0 with 2.15.3 version of our SDK. This could very likely be based on your app settings. Can you please make sure you have `multiDexEnabled` set to true as shown below in your gradle settings:

```gradle
android {
    defaultConfig {
       multiDexEnabled true
    }
}
```

**Comment by SalvatoreAD** [comment] 2017-10-30 18:06
Hi @jaypatel512 , the problem occurs with the gradle version 3.0. with the previous version of gradle there is no compilation error. I did not test if it works.

**Comment by santanaluiz** [comment] 2017-12-19 10:13
@SalvatoreAD did you manage to fix this?

**Comment by ashwinbhaskar** [comment] 2017-12-26 10:58
i am also facing this issue

**Comment by haemi** [comment] 2018-01-04 10:17
same here

**Comment by david-kariuki** [comment] 2018-01-05 08:16
I'Ve tried all means but I can't seem to find a solution.

**Comment by xiaoleih41** [comment] 2018-01-09 20:52
This SDK has been deprecated. If you are doing a new integration, please stop and look into Express checkout via Braintree SDK and Braintree direct product instead.  Please find more detail form the README.MD.

**Comment by KMiso** [comment] 2018-01-12 04:17
I am not familiar with android studio..
but using it to test AWS cognito
I've been trying to fix this error shown below..
No idea how to fix it so far...


FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by sali49258** [comment] 2018-01-21 22:30
I had similar issue, read many possible workaround nothing worked.  What worked is 
Solution#1) Create an application in release build configuration with and without signed apk - and then dex's are successfully merged into apk but still **debug** configuration was not working. 
Solution #2) Run and compile in debug mode with stack trace and info mode on , and see detailed warning and message and then trace back from there .  In my case , cognito files were reported as defined duplicated,  per suggestions from others on forum, I have deleted .gradle folder and lib folder of app and then after recompilation it worked .
Hope this will help someone else in debugging this issue.

**Comment by mansoorexpert** [comment] 2018-01-23 09:26
I find out the reason of this problem for my project. **_I was added one dependency twice in build.gradle_**. One time by adding dependency and one  time again by adding jar dependency:

**compile 'org.achartengine:achartengine:1.2.0'<br>
...<br>
implementation files('../achartengine-1.2.0.jar')**

after remove the first line problem solved.

**Comment by jaypatel512** [comment] 2018-01-23 17:17
Hey folks, 

I am trying to reproduce this problem so that I can pinpoint the issue. I have created a [very simple Android Project](https://github.com/jaypatel512/test) to reproduce the problem.

I would appreciate if anyone of you can help me replicate the issue you folks are seeing.

```
 $ ./gradlew --version

 ------------------------------------------------------------
 Gradle 4.1
 ------------------------------------------------------------

 Build time:   2017-08-07 14:38:48 UTC
 Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

 Groovy:       2.4.11
 Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
 JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
 OS:           Mac OS X 10.12.6 x86_64
 ```

 ```
 ./gradlew clean build

 > Task :app:lint
 Ran lint on variant release: 2 issues found
 Ran lint on variant debug: 2 issues found
 Wrote HTML report to file:///<>/reports/lint-results.html
 Wrote XML report to file:///<>/reports/lint-results.xml


 BUILD SUCCESSFUL in 28s
 58 actionable tasks: 56 executed, 2 up-to-date

 ```

**Comment by pp-randy** [comment] 2018-01-29 15:54
Is anyone able to help reproduce, please review the above comment https://github.com/paypal/PayPal-Android-SDK/issues/448#issuecomment-359863568?

**Comment by malcolmx18** [comment] 2018-03-11 03:23
i fix mine using the multidex

**Comment by Ayoubdesigner101** [comment] 2018-03-19 06:01
hey @jaypatel512 
I using this code 
android {
    defaultConfig {
       multiDexEnabled true
    }
}

but dont work and my error is:
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
can you help me

**Comment by yash365** [comment] 2018-03-29 09:00
i have tried,
android {
defaultConfig {
multiDexEnabled true
}
}

but getting same error

**Comment by achabiismail** [comment] 2018-04-05 23:19
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by clementiano9** [comment] 2018-04-19 11:55
I'm having this same issue after upgrading to Android studio 3.1.1 
Using android gradle plugin 3.1.1
buildToolsVersion 27.0.3 (minimum for Android studio 3.1.1)
compileSdkVersion 27

multiDexEnabled true doesn't help

**Comment by RezaMasoudi** [comment] 2018-04-27 20:19
multiDexEnabled true  did not work

**Comment by trr-amsiq** [comment] 2018-05-03 11:07
try ```android.enableD8 = false``` in ```grade.properties```

**Comment by kongsonida** [comment] 2018-05-03 14:56
I tried android.enableD8 = false in grade.properties, not work

**Comment by zainijmusic** [comment] 2018-05-03 18:58
im facing this probem

**Comment by Kahia007** [comment] 2018-05-06 23:47
hoow

**Comment by anh76qn** [comment] 2018-05-10 08:14
Is there no way to solve the problem?

**Comment by kjknair** [comment] 2018-05-10 08:58
I got the same problem . I already had multidex enabled and it started occuring after updating a sdk i was using.
```
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForProdDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```

**Comment by yashrajsharma23** [comment] 2018-05-14 13:29
Hello Everyone,
Here i am facing the same problem as below:
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

Please if someone has any kind of solution then please share it.

**Comment by komendantaa** [comment] 2018-06-06 11:33
I faced with this issue after adding facebook plugin.

Next steps are work for me:
1 remove android platform;
2 `ionic cordova prepare android`

**Comment by m-hcb** [comment] 2018-06-08 05:57
I somehow fixed it guys
Here is the solution that worked for me

1-> Add 
     defaultConfig {
           multiDexEnabled true
     }
2-> Check your dependencies list for any possible duplicate 
3-> Build -> Clean project
4-> Build -> Rebuild project
then try to run on your device.
I hope this will help.

**Comment by varunpandey1995** [comment] 2018-06-13 14:27
I had same Issue, 
In my case I am using two different libs, 
internally one lib using other lib, ie.(androidsvg-1.2.1.jar) which was causing problem,
just **removed the outer dependency**. and it worked fine.

**Comment by MaheshNandam** [comment] 2018-07-02 11:11
Below lines works for me,

compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}

**Comment by grace555** [comment] 2018-08-26 11:26
trr-amsiq  you saved my day! cheers!

**Closed** 2018-08-27 09:29 UTC

**Comment by armbrustsamuel** [comment] 2018-09-04 22:28
Also duplicated dependency 
implementation(name: 'slf4j-android-1.6.1-RC1', ext: 'jar')
@trr-amsiq @mansoorexpert , thank you!

**Comment by manojthayil46** [comment] 2018-09-23 09:39
I was working with firebase and got the same error .So I Just upgrade the app level dependencies to the latest versions and it worked for me

**Comment by Ayberkone** [comment] 2018-12-07 18:19
Guys. I've been trying to figure out this s. for 5 hours and my hands are shaking.
HOWEVER, I figured it out. Just go to your 'libs' folder and delete everything (I just did it for acra and it worked) but it woul be the best for you. Then, re-stack lib. 

Good luck eveyone!

**Comment by manojthayil46** [comment] 2018-12-07 18:23
1) clean and rebuild

2)Make sure you are using the latest versions of all the libraries in
build.gradle
