### ISSUE TITLE
Crash on start PayPalService

### ISSUE THREAD

**Issue by kroid333** [paypal/PayPal-Android-SDK#263] opened 2016-02-22 09:08 UTC
E/AndroidRuntime: java.lang.RuntimeException: Unable to start service com.paypal.android.sdk.payments.PayPalService@426c583 with Intent { cmp=com.flyonthego/com.paypal.android.sdk.payments.PayPalService (has extras) }: java.lang.IllegalStateException: Unable to extract the trust manager on okhttp3.internal.Platform$Android@439bfaf8, sslSocketFactory is class com.paypal.android.sdk.ck
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3000)
at android.app.ActivityThread.access$2200(ActivityThread.java:172)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5653)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)

E/AndroidRuntime: Caused by: java.lang.IllegalStateException: Unable to extract the trust manager on okhttp3.internal.Platform$Android@439bfaf8, sslSocketFactory is class com.paypal.android.sdk.ck
at okhttp3.OkHttpClient.(OkHttpClient.java:187)
at okhttp3.OkHttpClient.(OkHttpClient.java:60)
at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:718)
at com.paypal.android.sdk.cq.(Unknown Source)
at com.paypal.android.sdk.payments.PayPalService.a(Unknown Source)
at com.paypal.android.sdk.payments.PayPalService.onStartCommand(Unknown Source)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2983)
at android.app.ActivityThread.access$2200(ActivityThread.java:172) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:146) 
at android.app.ActivityThread.main(ActivityThread.java:5653) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
at dalvik.system.NativeStart.main(Native Method) 

crash after start service:
Intent intent = new Intent(getActivity(), PayPalService.class);
intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config);
getActivity().startService(intent);

**Comment by pp-randy** [comment] 2016-02-22 14:32
Closing as duplicate of https://github.com/paypal/PayPal-Android-SDK/issues/258

**Closed by pp-randy** 2016-02-22 14:32 UTC
