### ISSUE TITLE
Unexpected char 0x516b at 66 in User-Agent value

### ISSUE THREAD

**Issue by FrancescLlaoGarcia** [paypal/PayPal-Android-SDK#271] opened 2016-03-14 11:26 UTC
**OUR GRADLE:**
compile ('com.paypal.sdk:paypal-android-sdk:2.13.3'){
    exclude group: 'io.card'
}

**WHEN ERROR APPEARS:**
config = new PayPalConfiguration()
        .environment(PayPalConfiguration.ENVIRONMENT_PRODUCTION)
        .acceptCreditCards(false)
        .clientId(getString(R.string.paypal_client_id_live));

Intent intent = new Intent(this, PayPalService.class);
intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, config);
startService(intent);

**OUR CLIENT DEVICE:**
Teclast P89 3G (p893g_d1h8)

**OUR CLIENT ERROR:**
java.lang.IllegalArgumentException: Unexpected char 0x516b at 66 in User-Agent value: PayPalSDK/PayPal-Android-SDK 2.13.3 (Android 4.4.2; Teclast P89 3G八核(D1H8); )
at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:283)
at okhttp3.Headers$Builder.add(Headers.java:233)
at okhttp3.Request$Builder.addHeader(Request.java:177)
at com.paypal.android.sdk.cl.intercept(Unknown Source)
at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
at okhttp3.RealCall.access$100(RealCall.java:30)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

**Comment by jaypatel512** [comment] 2016-03-14 15:41
From the looks of it, it looks like the device name has a special character in it. Can you please help us confirm if you are not seeing the same issue on a different device with a non-special character please. 

Thanks.

**Comment by FrancescLlaoGarcia** [comment] 2016-03-14 17:24
The error was reported by a customer . Only happens on this device. It is a Chinese tablet.

**Comment by jaypatel512** [comment] 2016-03-15 18:03
Hey @FrancescLlaoGarcia !

I think that seems like an issue in SDK side. We do accept unicode characters, but for some reason, it may be causing this issue. I will go ahead and try to reproduce and fix this issue soon.

**Comment by sankarbhavanib** [comment] 2016-03-22 21:55
issue resolved in 2.14.0

**Closed by sankarbhavanib** 2016-03-22 21:55 UTC
Labels: bug
