### ISSUE TITLE
Payment with confirmation

### ISSUE THREAD

**Issue by spry** [paypal/PayPal-Android-SDK#152] opened 2015-03-20 03:23 UTC
I am able to produce a condition in the PayPal SDK a payment is posted to PayPal but no payment confirmation is returned. 

Steps to reproduce:
1. Initiate a single payment
2. Switch off wireless immediately and turn it back on (simulating poor network conditions)

Symptoms:
- Logs report SERVER_COMMUNICATION_ERROR
- When retrying, logs report failure with 400 Bad Request and DUPLICATE_REQUEST

This implies that the request reached the server, but a payment confirmation was not received by the client. Retrying the payment results in the logs reporting another DUPLICATE_REQUEST. The only way to exit from the PayPal SDK at this point is to cancel. On cancelling, no error is available and as such we cannot notifiy the user of what happened.

Do you have any suggestions of how to work around and/or fix this problem?

**Comment by mattjacunski** [comment] 2015-03-20 14:33
@spry - Thanks for reporting this.  I'd like to investigate this specific case, so can you share the entire error response?  This should include a PayPal-Debug-Id that will be useful.

**Comment by spry** [comment] 2015-03-24 01:09
@mattjacunski  Please see the attached image for the log.
![paypal log](https://cloud.githubusercontent.com/assets/35188/6793845/83c88692-d21e-11e4-80d6-c8c0cf56bb16.png)

**Comment by mattjacunski** [comment] 2015-03-25 12:37
Thanks for reporting this - it looks like an issue in the SDK.  I will post back to this thread with progress.

**Comment by mattjacunski** [comment] 2015-05-05 15:43
@spry - I am investigating this issue but want more details on exactly when you are switching off wireless.  Is it after logging in when the payment is created and the user is presented with shipping addresses and funding options?  Or is it when the user click`Pay`?

**Comment by geeknam** [comment] 2015-05-29 00:50
Hey @mattjacunski, these are steps to reproduce.

STEPS TO REPRODUCE
-----------------------------
1. Go to checkout, use Paypal as payment option
2. Login to Paypal account
3. Tap "Send Payment" + QUICKLY switch off the WIFI
4. Switch on WIFI again.
5. Paypal shows "There was a problem communicating with Paypal servers. Please try again."
6. Tap "Send Payment" again to pay
7. Paypal shows "Duplicate transaction"
8. Customer presses "Cancel" --> Paypal activity gets dismissed, customers are shown an empty screen with loading bar "Finalising your order"

**Comment by jaypatel512** [comment] 2015-08-17 19:48
Hey @geeknam , @spry !

Can you confirm if you are seeing this only when the invoice_number is provided ? I think I was able to reproduce this issue, but only when the invoice_number was passed.

**Comment by jaypatel512** [comment] 2015-09-01 18:02
Any update @geeknam @spry ??

**Comment by ppmtscory** [comment] 2015-09-28 15:28
The error states that it has to do with a duplicate invoice ID, hence closing this issue.  As a way to handle this, if you get that error, you can do a quick query to get a [list of payments](https://developer.paypal.com/docs/api/#list-payment-resources).  Once you find the initial payment request, you should be able to get the status.

**Closed by ppmtscory** 2015-09-28 15:28 UTC
Labels: bug

**Comment by dayforu10** [comment] 2015-10-07 20:05
barbaraDay
